trigger: none

#pool: 
#  name: Default
#  demands:
#    - agent.name -equals TestBuildArtifact

pool: 
    vmImage: 'windows-latest'

steps:

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: 'Build & Publish'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'Build & Publish'
    downloadPath: '$(Pipeline.Workspace)'