trigger: none

#pool: 
#  name: Default
#  demands:
#    - agent.name -equals TestBuildArtifact

pool: 
    vmImage: 'windows-latest'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: echo "HELLO WORLD"
